services:

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
  
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend